export type GoogleReview = {
  id: number
  name: string
  quote: string
  rating: number
  source: string
}

export const googleReviewSummary = {
  rating: 4.9,
  totalReviews: 164,
  fiveStarCount: 161,
}

export const topFiveStarReviews: GoogleReview[] = [
  {
    id: 1,
    name: "Shawn Mulligan",
    rating: 5,
    source: "Google Review",
    quote:
      "I received a procedural root canal yesterday, and the level of professionalism throughout the entire experience was exceptional. From start to finish, everything was handled with precision and care, and the procedure was absolutely painless. Today, there is no post-procedure pain at all. The team was calm, efficient, and clearly highly skilled. If I ever develop another issue requiring an endodontist, I will absolutely seek the support of Dr. Anderson and his team.",
  },
  {
    id: 2,
    name: "Stephen Bramfitt",
    rating: 5,
    source: "Google Review",
    quote:
      "Second-time patient. What strikes me from both of my appointments is the professionalism in every aspect of my experiences. From Erin the receptionist to Gwen the assistant to Doctor Anderson himself, everyone is focused, pleasant, and efficient. Frankly, I see this so rarely (including in my own profession), that it's kind of refreshing --- and we're talking about oral surgery here! Nothing but props!",
  },
  {
    id: 3,
    name: "Donna Rose",
    rating: 5,
    source: "Google Review",
    quote:
      "No one wants a root canal, but if it's needed, this is the practice I would recommend. Professionalism is primary. All the staff, especially Dr. Anderson, was skilled, knowledgeable, kind, fun. This visit was part of an attempt to save a tooth that my long time regular dentist has recommended a crown. In addition to the initial specialized exam, Dr. Anderson discovered other health issues that I needed to attend to that I was completely unaware of. I felt very fortunate that he was so meticulous and observant. I would not hesitate to contact him if I had any issues in the future. The specialized dental equipment in this office is top notch and Dr. Anderson and staff really know how to use it for the benefit of their patients. Highly recommend!",
  },
  {
    id: 4,
    name: "Leticia Martinez",
    rating: 5,
    source: "Google Review",
    quote:
      "I had a root canal done recently, and the experience was far better than I expected. I felt back to normal 1 hour after a root canal procedure, which was amazing. The procedure itself was very comfortable and absolutely no pain. The dentist explained everything and made sure I felt at ease the entire time. Thank you so much Dr Anderson and the lovely staff!",
  },
  {
    id: 5,
    name: "S Johnston",
    rating: 5,
    source: "Google Review",
    quote: "I had a great experience. Dr. Anderson and the team are very skilled and made me feel at ease. I felt no pain. I would highly recommend them.",
  },
  {
    id: 6,
    name: "Kay White",
    rating: 5,
    source: "Google Review",
    quote:
      "My recent consult was promptly scheduled and well-arranged. Dr Anderson is a caring and experienced professional. He tailored my exam to my medical history, foregoing what is now routine, a CT scan. He diagnosed my tooth status quickly (unlike 2 previous dentists). His office manager has organized patient and doctor forms well with preparation serving both patient and office needs. This was an excellent experience for me.",
  },
  {
    id: 7,
    name: "David Guenette",
    rating: 5,
    source: "Google Review",
    quote:
      "A big thank you to Dr. Anderson and his staff. Everything went smoothly and with such a complex procedure where pain is expected, there was really very minimal discomfort. Aside from a brief mild ache post op, I feel fantastic.",
  },
  {
    id: 8,
    name: "G Manning",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr Anderson was very thorough and methodical, his team are fantastic. I never thought I'd say I like a root canal dentist but I was very impressed. Dr. Anderson takes a very thorough, methodical approach, and the entire team works hard to make an uncomfortable situation as easy as possible. Highly recommend!",
  },
  {
    id: 9,
    name: "Sharon",
    rating: 5,
    source: "Google Review",
    quote:
      "Highly Recommend! Let's be honest, no one is ever thrilled about getting a root canal. But, Dr Anderson and his staff made it a breeze! In spite of having a stubborn tooth that needed a lot of attention, I felt completely comfortable and well cared for. My tooth anatomy was challenging, and Dr. Anderson came to my rescue. I couldn't recommend him any more highly!",
  },
  {
    id: 10,
    name: "Lizandro Reyes",
    rating: 5,
    source: "Google Review",
    quote:
      "They are the best! I had an awful tooth infection that needed a root canal, I contacted their office and they were able to fit me in first thing in the morning the very next day. They answered any questions I had prior to the procedure and made me feel very comfortable. Best of all, the procedure was quick and painless. Dr Anderson and his staff are the best, very clean office and high quality work. Do yourself a favor and come see them for all your dental needs. Thank you guys so much!",
  },
  {
    id: 11,
    name: "Sita Zarcufsky",
    rating: 5,
    source: "Google Review",
    quote:
      "From the first phone call to Dr. Anderson's office to days after my root canal, all I can describe is a wonderful experience. The staff was incredibly informative, kind, and friendly. The root canal itself was my third, and by far the best experience of all. Dr. Anderson and his staff have and will continue to strive to provide the best endodontic dental care possible to all of his patients. Thank you Wine Country Root Canal Specialist!",
  },
  {
    id: 12,
    name: "Jordan S",
    rating: 5,
    source: "Google Review",
    quote: "I had a positive experience at this office! The work I had done went smoothly, clean office and supportive staff. Highly recommend.",
  },
  {
    id: 13,
    name: "N. G.",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson and his team made my root canal experience very pleasant. I feel confident that he performed excellent work on my problem tooth and I felt very safe during the procedure. In the event that I ever need a root canal again, I will be setting an appointment with Dr. Anderson!",
  },
  {
    id: 14,
    name: "Arminée Chahbazian",
    rating: 5,
    source: "Google Review",
    quote:
      "My experience with Dr Anderson and the staff was superb. They got me in for an appointment within 3 hours and explained the root canal process thoroughly. It was a peaceful environment and I felt like I was in excellent hands. I experienced no pain during or after the procedure. If you need a root canal I can honestly say I highly recommend Dr Anderson and his team!",
  },
  {
    id: 15,
    name: "SEAsia Moto",
    rating: 5,
    source: "Google Review",
    quote:
      "One of my best dental experiences having the pleasure to meet Dr Anderson. His attention to detail, precise work and process, polite demeanor and professional attitude are at the highest level. The work is also done with the unquestionable latest technology available today. I highly recommend him and his team for any endodontic work you may need. Thank you Dr Anderson and your wonderful staff!",
  },
  {
    id: 16,
    name: "William Grafeld",
    rating: 5,
    source: "Google Review",
    quote:
      "Wow!!! Going to an Endodontist for a root canal was something I wanted to avoid. Just thinking of the procedure raised my blood pressure. Dr. Anderson calmed me down and after a 'few visits' to his office, I was ready for the procedure. His expert touch and the latest technology made it a painless and very positive experience. I highly recommend Dr. Anderson and his very professional staff. Thank you guys!",
  },
  {
    id: 17,
    name: "Diane DeStefano",
    rating: 5,
    source: "Google Review",
    quote:
      "I was referred to Dr. Anderson by my long-time dentist, whom I greatly trust, and I'm grateful I was sent to his office. Dr. Anderson and his staff are incredibly warm, kind and very professional. Dr. Anderson clearly explained everything before starting and I felt very comfortable throughout the procedure. I am extremely pleased with the results and will definitely return if I ever need another root canal. Highly recommended!",
  },
  {
    id: 18,
    name: "Sarit Rubenstein",
    rating: 5,
    source: "Google Review",
    quote:
      "I HIGHLY recommend Dr. Anderson! What an AMAZING experience! From the front desk staff who was so sweet and welcoming, to the nurse helping the dr. who was kind and friendly, to Dr. Anderson who was professional, caring, and took the time to explain everything to me. He made sure I was comfortable throughout the entire process. I've had root canals before, but none were as easy and painless as this one. Thank you Dr. Anderson and your wonderful staff!",
  },
  {
    id: 19,
    name: "Gerry Kelsall",
    rating: 5,
    source: "Google Review",
    quote:
      "I came in in pain, and left comfortable. The procedure was painless, the doctor explained everything he was doing in advance, and the staff was friendly and very competent. Having a root canal is not something I look forward to, but this office made it as positive as possible. I would definitely recommend Dr Anderson to anyone needing a root canal. Thank you for the great care!",
  },
  {
    id: 20,
    name: "Maxwell May",
    rating: 5,
    source: "Google Review",
    quote:
      "My experience was incredible with Dr. Anderson. I needed a root canal and it was performed over 3 appointments. During each appointment Dr. Anderson was methodical, professional, and extremely skilled. He even called me hours after the procedure to make sure I was doing okay. I cannot say enough good things about Dr. Anderson and his staff. If you need a root canal, this is the place to go!",
  },
  {
    id: 21,
    name: "JW Chang Mayo",
    rating: 5,
    source: "Google Review",
    quote:
      "I was referred to Dr Anderson by another great dentist (Martin Allaire, DDS) for a root canal consultation. Judy at the front office was so welcoming, efficient and competent. His dental nurse Connie was a calm presence and so friendly. Dr. Anderson took care of my root canal in the most compassionate manner. His receptionist Tom was very kind to me and made my experience at the dentist office pleasant. I highly recommend this office for any endodontic needs!",
  },
  {
    id: 22,
    name: "Katie Schwartz",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson is one of the best doctors I've ever seen. I absolutely LOVE and APPRECIATE him so much. He's calming, professional, kind, compassionate and gentle. He listens to his patients. Dr. Anderson is also thorough and detail oriented. His staff is just as wonderful as he is. If you're looking for an amazing endodontist, look no further! I can't recommend him highly enough!",
  },
  {
    id: 23,
    name: "Ian Abrams",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson conducted a thorough examination, discovered what my real problem was, explain things thoroughly and told me what my next steps should be. I was very impressed by his professionalism and care. The office is clean and equipped with the latest technology. The staff is friendly and efficient. I highly recommend Dr Anderson and his team for anyone needing endodontic care. Thank you for a great experience!",
  },
  {
    id: 24,
    name: "Carrie Lukacic",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson and his staff were amazing. I came to the office with a root canal partially done by my family dentist. The referral was exactly what I need. My tooth anatomy was challenging, and Dr. Anderson came to my rescue. I couldn't recommend him any more highly! The procedure was painless and the results are fantastic. Thank you for saving my tooth!",
  },
  {
    id: 25,
    name: "Zorica",
    rating: 5,
    source: "Google Review",
    quote:
      "I was in need of an emergency root canal and Dr. Anderson's office was able to fit me in. The staff was incredibly helpful and kind. Dr. Anderson was very thorough and explained the entire procedure to me. I was a bit nervous, but he made me feel at ease. The root canal was painless and I felt much better afterwards. I would highly recommend Dr Anderson and his team to anyone!",
  },
  {
    id: 26,
    name: "Ann Lasley",
    rating: 5,
    source: "Google Review",
    quote:
      "Friendly staff and Dr was very professional and non judgmental. Was in a lot of pain and my regular dentist office was closed. They took me in right away and addressed my concerns. They were able to help me pinpoint the problem and put my mind at rest that it was not more serious. First impressions are important and they gave me a great comfortable and welcoming feeling. Thank you.",
  },
  {
    id: 27,
    name: "Daniel Gonzalez",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 28,
    name: "Dats Nismo",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 29,
    name: "MIKEY",
    rating: 5,
    source: "Google Review",
    quote:
      "I had a wonderful experience at Wine Country Root Canal. I can't believe I describe a root canal as wonderful. Absolutely no pain during the procedure. The staff is very nice and attentive. I really liked how Dr Anderson was so polite to his staff and me. Also I felt safe having to have this procedure during a pandemic. They follow safety procedures. Liz Decker",
  },
  {
    id: 30,
    name: "adam treiber",
    rating: 5,
    source: "Google Review",
    quote: "Thank you to all for your professional service, communication during the procedure, and follow up.",
  },
  {
    id: 31,
    name: "Jesse Martinez",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. explained to me everything he was going to do in detail. He was very patient and kind and caring along with the staff. Highly recommend this place to anyone.",
  },
  {
    id: 32,
    name: "Mora Cronin",
    rating: 5,
    source: "Google Review",
    quote:
      "Thoroughly professional from start to finish. Doctor and nurse explained the procedure as it progressed, and other than a tired jaw, it was a pain-free experience. If you have to have a root canal, I can highly recommend Dr. Anderson and his practice.",
  },
  {
    id: 33,
    name: "Justine Haugen",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 34,
    name: "Kent Wilson",
    rating: 5,
    source: "Google Review",
    quote:
      "Transplanted form SOCAL, Dr. Anderson is obviously a master at his craft. Professional. No ill effects. No pain after two days! I was expecting a wine tasting since the appellation, 'Wine Country Root Canal,' but alas, no samples after the procedure! But no better place on earth for a root canal.",
  },
  {
    id: 35,
    name: "Carla Trotter",
    rating: 5,
    source: "Google Review",
    quote: "I found Dr Anderson to be thorough, kind, respectful & honest. I could not recommend a better dental professional.",
  },
  {
    id: 36,
    name: "Isabel Meisler",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 37,
    name: "Veronica Flores",
    rating: 5,
    source: "Google Review",
    quote: "Very courteous and professional, I felt welcomed.",
  },
  {
    id: 38,
    name: "Eric Kritz",
    rating: 5,
    source: "Google Review",
    quote:
      "I was extremely impressed with Dr. Anderson and his thoroughly professional staff. I was particularly impressed with the level of communication from everyone- all of my questions were answered. Thanks for a wonderful experience...",
  },
  {
    id: 39,
    name: "Madison Capps",
    rating: 5,
    source: "Google Review",
    quote:
      "I had Dr yadegr helping me yesterday and I couldn't be more thankful for him. I was a last minute add into his schedule and he didn't rush me or make me feel unwelcome. He took such amazing care of me and I am truly thankful I was referred to him.",
  },
  {
    id: 40,
    name: "Edward Yang",
    rating: 5,
    source: "Google Review",
    quote: "Very very professional. I will travel all the way to Santa Rosa to get his treatment.",
  },
  {
    id: 41,
    name: "Grisel Buendia",
    rating: 5,
    source: "Google Review",
    quote:
      "The best dental experience I've EVER had. I wish Dr. Yadegar was a General dentist because I'd switch doctors right away.",
  },
  {
    id: 42,
    name: "Erika Lee Kline",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Joshua Yadegar made sure I was comfortable, pain free and informed before, during and after the procedure. He was confident in the root canal he performed on my tooth. My dentist referred and recommended Dr. Yadegar and was available to collaborate with him during my appointment. I felt at ease during the process and was thankful and impressed with the care I was provided.",
  },
  {
    id: 43,
    name: "Oscar Orrego",
    rating: 5,
    source: "Google Review",
    quote:
      "It was my best experience with a dentist. Doctor Anderson explains everything in detail. I had no pain from beginning to end. The staff are very nice and the place is clean. I am thankful and would highly recommend him.",
  },
  {
    id: 44,
    name: "Stephney Brigman",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 45,
    name: "Connie Nau",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 46,
    name: "Zach Hoogerland",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson is fantastic. He makes such an effort with his patients - he will even call you after your visit to ensure that you are doing ok. The office staff is accommodating and friendly.",
  },
  {
    id: 47,
    name: "Gary Mittman",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 48,
    name: "Zorica Rutovic",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr Anderson took care of my root canal in the most companionate manner. His receptionist Tom was very kind to me and made my experience at the dentist office pleasant. I would recommend Dr Anderson to my friends and family.",
  },
  {
    id: 49,
    name: "Randy Averso",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 50,
    name: "Phyllis Zimbler Miller",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 51,
    name: "Courtney Caron",
    rating: 5,
    source: "Google Review",
    quote:
      "I had some rather detailed and unexpected dental work to be completed. Dr. Anderson and his team were wonderful. From the moment I walked in, I was handled with thoughtfulness and care. The dental work was meticulously performed. Highly recommend.",
  },
  {
    id: 52,
    name: "Josh Jones",
    rating: 5,
    source: "Google Review",
    quote:
      "Fantastic dentistry! I hate going to the dentist. The thought pains me, just as much if not worse than going to the DMV. My 3rd visit is tomorrow and I couldn't be happier. Dr. Anderson and his team have taken great care of me. The doctor himself is calm, cool, and collected which goes a long way to make me feel confident that my money, time, and self is making a good investment. I'm currently visiting for a root canal that was more inflamed than needed. Instead of just rushing through the procedure the DR spread out the treatment plan over several days to allow my body time to heal and be ready for the full procedure. No added fees for this. It's been smooth sailing and the final steps to come. Should something change I'll update this review but I doubt anything will go wrong. I hope everyone else has as good of an experience as I'm having.",
  },
  {
    id: 53,
    name: "Ann Troxell",
    rating: 5,
    source: "Google Review",
    quote:
      "Its hard to give a 5 star review for a root canal but Dr. Anderson and his staff were great. Very organized and professional and no pain during the procedure. Good follow up and willing to answer any and all questions.",
  },
  {
    id: 54,
    name: "Jesse Ward",
    rating: 5,
    source: "Google Review",
    quote: "Friendly staff, were able to accommodate me same day, doctor extremely competent and took his time answering all my questions.",
  },
  {
    id: 55,
    name: "Natalie Strauss",
    rating: 5,
    source: "Google Review",
    quote: "I never thought a root canal would be relaxing, but that's exactly what it was. Very calm and reassuring staff. Would go again if I ever needed :)",
  },
  {
    id: 56,
    name: "Lauren Tucker",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 57,
    name: "Ryan Boyd",
    rating: 5,
    source: "Google Review",
    quote: "Very professional, personal and pleasant.",
  },
  {
    id: 58,
    name: "Lenny Lambersky",
    rating: 5,
    source: "Google Review",
    quote: "FIRST CLASS ABSOLUTELY THE BEST",
  },
  {
    id: 59,
    name: "Adam Xiao",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 60,
    name: "Sharon Seyoum",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 61,
    name: "Marta Bailey",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson took me in on a semi-emergency basis. His staff was most helpful and professional. I am on the road to recovery even though I require 2 more visits to finish the process. I feel 100% better already and won't hesitate to call the doctor sooner if the need arises again. I was hoping the problem would go away on its own. Well, that rarely happens. Word to the wise: Call the doctor sooner rather than later.",
  },
  {
    id: 62,
    name: "Spencer Wilcox",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 63,
    name: "barbara dorfman",
    rating: 5,
    source: "Google Review",
    quote: "Experience was very good. In and out in an hour.",
  },
  {
    id: 64,
    name: "K W",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr Anderson was very nice and professional. He made sure I was comfortable throughout the entire procedure and even used rubber dam clamp to avoid getting any debris in my mouth while working on my tooth. He also called later that evening to check on how I was recovering. Overall, a great experience but hopefully my last root canal.",
  },
  {
    id: 65,
    name: "Judy Keaney",
    rating: 5,
    source: "Google Review",
    quote:
      "Wonderful experience from the beginning with a very through and complete insight as to my coverage and my appointment. Easy form completion via ipad. Great staff and dentist. Dr. Anderson was attentive, kind person that ensured that I was comfortable as possible during my root canal. All round great care.",
  },
  {
    id: 66,
    name: "Curt Boswell",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 67,
    name: "Dr. Timothy Gogan",
    rating: 5,
    source: "Google Review",
    quote: "Excellent work. Gentle, fast and very thorough!",
  },
  {
    id: 68,
    name: "Daniel Lacesa",
    rating: 5,
    source: "Google Review",
    quote: "Fantastic experience amazing dentist and staff! Thank you dr. Anderson! No more dental anxiety!",
  },
  {
    id: 69,
    name: "Rene Deloffre",
    rating: 5,
    source: "Google Review",
    quote:
      "RENE DELOFFRE I was referred to Dr. Anderson by my regular dentist Dr. Robert Battan, the most honest dentist I ever came across. Well, great dentists tend to hang around with other competant professionals so is there any surprise I've found myself more than once, in Dr. Anderson's special root canal chair?",
  },
  {
    id: 70,
    name: "Chelsea Montgomery-Duban Waechter",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 71,
    name: "naomi goldrich",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 72,
    name: "Sabrina Bassett",
    rating: 5,
    source: "Google Review",
    quote:
      "Dr. Anderson and his staff are wonderful. They immediately put me at ease, answered my questions, and most importantly provided high quality care to treat my tooth infection. I cannot recommend highly enough!",
  },
  {
    id: 73,
    name: "Fred Rose",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 74,
    name: "Getzy R",
    rating: 5,
    source: "Google Review",
    quote: "Great",
  },
  {
    id: 75,
    name: "tom hamlin",
    rating: 5,
    source: "Google Review",
    quote: "I was able to get my root canal on the same day of my apointment with great reults---thanks Dr Anderson",
  },
  {
    id: 76,
    name: "Bill Haugse",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 77,
    name: "Sofia",
    rating: 5,
    source: "Google Review",
    quote:
      "So happy I found Doctor Anderson! He was friendly, knowledgeable and most importantly caring! I felt very comfortable with him preforming my root canal procesure which was less painful than I anticipated! The entire staff was very friendly.",
  },
  {
    id: 78,
    name: "Jennifer C",
    rating: 5,
    source: "Google Review",
    quote:
      "Like many people today I found Dr. Anderson by online reading all of his positive reviews. I had a problematic tooth that had been through two failed root canals by another dentist. Dr. Anderson listened to the history and was able to successfully redo the root canal and treat the infection. He was very skilled and focused while he worked and incredibly, I felt no pain when gave me the Novocaine shots or during the procedure. He also called me after the procedure to check in. The office staff Ruby and Kelly were both kind and professional and followed up with an email report of the procedure that included an x ray of the tooth. I highly recommend Dr. Anderson for a root canal.",
  },
  {
    id: 79,
    name: "Jonathan DePaz",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 80,
    name: "RoseMary Romero",
    rating: 5,
    source: "Google Review",
    quote:
      "Thank you Dr Anderson. You and your staff are very kind and considerate. A special thanks to Kelly for her reminder call to me to take my medication before my visit.",
  },
  {
    id: 81,
    name: "Mona Kassem",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 82,
    name: "Lisa Riboli",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson was skilled, professional, sterile, and took great care with my recent (and only) root canal. He phoned the next day on his day off to see how I was doing. Erin and Gwen are both lovely and added to the friendly and professional office. Outside the office you're greeted by a serene grove of towering redwoods rising through the center of the walkway.",
  },
  {
    id: 83,
    name: "Ren Ta",
    rating: 5,
    source: "Google Review",
    quote: "Highly recommended. Kind, informative, and a detailed oriented practice. My initial referral for a back molar that I desperately wanted to keep, Dr. Anderson's diagnosis was honest and in my best interest. The root canal I was hoping for to save said tooth did not have a solid enough outcome so he declined treatment. In the diagnostics with his state of the art equipment he did find a troubled root on a tooth that years earlier been damaged in an accident. Fast forward almost two years, and that tooth I wasn't even worried about started to give me grief, and he saved it. I am very thankful for his service and his high standards and warm professional staff.",
  },
  {
    id: 84,
    name: "Iran Meza",
    rating: 5,
    source: "Google Review",
    quote: "great experience. friendly and professional",
  },
  {
    id: 85,
    name: "Carol Smallen",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 86,
    name: "Jackie Mullis",
    rating: 5,
    source: "Google Review",
    quote: "The staff was so incredible, they handled my issue with expertise and understanding. Highly recommend!",
  },
  {
    id: 87,
    name: "Blaire Murphy",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 88,
    name: "Kimberly Johnson",
    rating: 5,
    source: "Google Review",
    quote: "Professional, friendly, competent staff. Checked in with me during procedure to ensure I was doing alright and follow up the next day. Highly recommend Dr. Anderson and his team, Thank you for taking such excellent care of me!",
  },
  {
    id: 89,
    name: "Jessica Mccahon",
    rating: 5,
    source: "Google Review",
    quote: "This clinic was a pleasure to work with. Came here for my first root canal and was treated kindly and compassionately. I highly recommend Dr. Anderson.",
  },
  {
    id: 90,
    name: "Eric Chesky",
    rating: 5,
    source: "Google Review",
    quote: "Entire office and Dr. Anderson are extremely professional and thorough. They are patient and explain all details and options available to the patient. Highly recommend.",
  },
  {
    id: 91,
    name: "Jonathan Parnell",
    rating: 5,
    source: "Google Review",
    quote: "Professional staff with state of the art equipment. I was referred by my dentist and really appreciated their attention to detail and well-coordinated care.",
  },
  {
    id: 92,
    name: "Carlos Menjivar",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 93,
    name: "Caleb Whitted",
    rating: 5,
    source: "Google Review",
    quote: "Amazing! No need to fear a root canal here!! Staff awesome! Dr awesome!",
  },
  {
    id: 94,
    name: "Jenna Merrow",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 95,
    name: "Greta Zeit",
    rating: 5,
    source: "Google Review",
    quote: "Erin, the receptionist is very helpful and friendly and knowledgeable and made me feel important and cared for. Dr Anderson and Suzanne performed the procedure as a tightly coordinated team. They acted like a single person with four hands. They were extremely attentive to my needs and did an excellent job. I did a mind exercise during the procedure thinking of all the things that I would like less than than a root canal. It made the time go faster and the aftermath was easy. I hope not to have to do this again but would choose to come here again if I needed another procedure.",
  },
  {
    id: 96,
    name: "Angela Rachelle",
    rating: 5,
    source: "Google Review",
    quote: "Getting a root canal is not a fun experience, but getting one done by someone who effortlessly makes you feel at ease and is a master of his craft, definitely makes the experience easier. I felt no pain, (not even when he was putting the Novocain in), he asked a ton of questions, walked me through everything he was doing and made sure I was comfortable for the 2 hours I was with him. I highly recommend Dr. Anderson and will go back to him again. If you have to get any kind of dental surgery or specialization done, this is your guy.",
  },
  {
    id: 97,
    name: "Linda Perez",
    rating: 5,
    source: "Google Review",
    quote: "Dr.Anderson is so patient and understanding, I am terrified when I go to the dentist but he makes me feel comfortable and is very patient with me!",
  },
  {
    id: 98,
    name: "Anne Tarbox Hall",
    rating: 5,
    source: "Google Review",
    quote: "Dr Anderson was extremely flexible & accommodating as I contacted him for an emergency root canal. I needed to see him within 48 hours as I left for a 3 month long trip in 2 days. Remarkably, despite a full schedule he saw me immediately, explained my options under these complicated circumstances and guided me as I chose the smartest option for me. He performed the root canal with care and expertise. He was thorough and efficient with explanations and advice. I am extremely grateful.",
  },
  {
    id: 99,
    name: "josh aizenman",
    rating: 5,
    source: "Google Review",
    quote: "First rate, timely help, and as painless as possible.",
  },
  {
    id: 100,
    name: "michael dyse",
    rating: 5,
    source: "Google Review",
    quote: "Office is very clean and relaxing. The staff is really nice and very professional. Dr. Anderson was honest, direct, and respectful of my time. I can't ask for more.",
  },
  {
    id: 101,
    name: "aimee caballero",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson and his staff are amazing! I went in for a root canal and the process went smooth. Would highly recommend this office for anyone who is looking for specialist.",
  },
  {
    id: 102,
    name: "Charlotte Offsay",
    rating: 5,
    source: "Google Review",
    quote: "I was very impressed by the level of care. The staff were kind, friendly and fit me right in when I needed a root canal. They walked me through the process and were quick and courteous. They then also called that evening to make sure I was doing well. I highly recommend Anderson DDS.",
  },
  {
    id: 103,
    name: "Jeremiah Childers",
    rating: 5,
    source: "Google Review",
    quote: "The best dentist experience I've had. Dr. Anderson fit me in on short notice, diagnosed the problem quickly, and carefully explained how he wanted to approach the problem and why. Couldn't recommend him more highly.",
  },
  {
    id: 104,
    name: "Siena Freitag",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 105,
    name: "Charles Tolman",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 106,
    name: "Catherine Baskerville",
    rating: 5,
    source: "Google Review",
    quote: "After my 11 year old son broke his front tooth while body surfing, Dr. Anderson did a root canal on very short notice. His calm demeanor really helped my son relax, and it's obvious he cares a lot about his patients.",
  },
  {
    id: 107,
    name: "John Bordeaux",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 108,
    name: "Julie Supple",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 109,
    name: "Candie Quach",
    rating: 5,
    source: "Google Review",
    quote: "Great service, friendly staff and caring doctor",
  },
  {
    id: 110,
    name: "Noel Jones",
    rating: 5,
    source: "Google Review",
    quote: "Absolutely professional but sensitive to the point, where I experienced no trepidation about what was coming next. As good an experience as possible considering my dental dilemma.",
  },
  {
    id: 111,
    name: "Bruce Mitteldorf",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Abbott knows what he's doing. I had a horrible toothache in a tooth that had already had a root canal about 20 years prior. My regular dentist took X-rays and thought the tooth was probably cracked, even though no crack was visible. He said I'd probably need to get the tooth pulled, but he referred me to Dr. Abbott for a 2nd opinion. Dr. Abbott's opinion was it was more likely a faulty root canal that had become infected. He explained in detail. A week later, after a course of antibiotics, he dug in and fixed the problem, and the tooth is now functional and pain-free. Having a root canal repair was no picnic, but the anaesthetic worked well, I still have the tooth, and no more toothache!",
  },
  {
    id: 112,
    name: "steve stabler",
    rating: 5,
    source: "Google Review",
    quote: "A very dedicated and caring doctor.",
  },
  {
    id: 113,
    name: "Joni Rae Russell",
    rating: 5,
    source: "Google Review",
    quote: "Dr Anderson is a knowledgeable, concerned and compassionate expert who will get to the bottom of your issue with excellent care, sensitivity and determination. He is at the top of his profession - if you are in need of an endodontist, it does not get better than Dr Anderson.",
  },
  {
    id: 114,
    name: "Joliene Hamodot Anavim",
    rating: 5,
    source: "Google Review",
    quote: "\"I can't wait to get a root canal\" Said no one ever! But if you have to see an Endodontist, go to Dr. Anderson. He squeezed me in for an emergency root canal and was so caring, gentle, and accommodating. His staff were fabulous too! He really helped to alleviate any fears and anxiety i had around my emergency visit. I would definitely recommend Dr. Anderson to anyone in search of an Endodontist.",
  },
  {
    id: 115,
    name: "kirbytepper",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson and his staff could not be more knowledgeable and professional. And they really are perfect for people who are uncomfortable with dentists. Great all around.",
  },
  {
    id: 116,
    name: "Jonathan Lewis",
    rating: 5,
    source: "Google Review",
    quote: "A very caring and detailed oriented doctor. I would recommend him without hesitation",
  },
  {
    id: 117,
    name: "Gwynne Evans",
    rating: 5,
    source: "Google Review",
    quote: "Entire office staff was wonderful. Most importantly, Dr. Anderson never made me feel rushed. I felt listened to and taken care of. Totally excellent experience. I would recommend him anytime.",
  },
  {
    id: 118,
    name: "Laura Hay",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 119,
    name: "Paul Broucek",
    rating: 5,
    source: "Google Review",
    quote: "Totally professional and first rate practice - kind & professional. Thanks!",
  },
  {
    id: 120,
    name: "Jerry Baker",
    rating: 5,
    source: "Google Review",
    quote: "Was sent here after my trip to the dentist revealed the need for a root canal. The work was painless and they did their best to make sure I was comfortable during the entire procedure. Would absolutely recommend",
  },
  {
    id: 121,
    name: "Leon Brooks",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 122,
    name: "Aaron Sokol",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 123,
    name: "Scottie Wardell",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 124,
    name: "yoshiko Gregg",
    rating: 5,
    source: "Google Review",
    quote: "I don't know which Dentist is good or no good. And don't like to be at Dentist. However, I felt like I found one of the best Dentist in LA today. I thought I can trust Dr. Anderson totally. He was very professional and gentle. Even after I had Root canal, no pain without any pain killers. I would very happy to recommend to my all my friends Dr. Anderson. Thank you for great work!",
  },
  {
    id: 125,
    name: "Max Rad",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 126,
    name: "Mike Nicholson",
    rating: 5,
    source: "Google Review",
    quote: "First time to Dr. Anderson & was for emergency abscessed tooth causing major pain. Squeezed me in 2 hours after call, out of pain in 3 hours. Two more follow up appointments for root canal in the next week, and all good. Fabulous staff, fabulous Endodontist!",
  },
  {
    id: 127,
    name: "josieclone Baker",
    rating: 5,
    source: "Google Review",
    quote: "Best Dentist ever -- most skilled, most knowledgeable, most adept at numbing the gum. Kind, caring, attentive. Personally calls back to follow-up. Thank you, Dr Craig!",
  },
  {
    id: 128,
    name: "Roger Raskin",
    rating: 5,
    source: "Google Review",
    quote: "Dr Anderson is the most AMAZING Endodontists in the buisness period. If your looking for perfection and greatness look no further. Oh did I mention he's the sweetest man you would ever want to meet. I highly recommend Dr Craig Anderson.",
  },
  {
    id: 129,
    name: "Cristina Guzman",
    rating: 5,
    source: "Google Review",
    quote: "The whole team is very kind. Dr. Anderson is awesome! I'm very thankful to be in good hands.",
  },
  {
    id: 130,
    name: "Andrew Ross",
    rating: 5,
    source: "Google Review",
    quote: "Awesome customer care",
  },
  {
    id: 131,
    name: "Michael Ritorto",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 132,
    name: "John Rossant",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson is everything you want in an endodontist. He works amazingly well and fast and explains everything in a calm voice as he works. He treated me as an intelligent adult rather than in a patronizing manner the way some doctors do.",
  },
  {
    id: 133,
    name: "Erol Ugljanin",
    rating: 5,
    source: "Google Review",
    quote: "Amazing service all around!! He and his team made me feel very comfortable and the treatment went so smooth. Would definitely recommend Dr. Anderson to anyone!",
  },
  {
    id: 134,
    name: "Kazu Suzuki",
    rating: 5,
    source: "Google Review",
    quote: "Courteous staff. Clean office. Doctor was easy to talk to & explained the treatment plans to me in details.",
  },
  {
    id: 135,
    name: "Paris R",
    rating: 5,
    source: "Google Review",
    quote: "Outstanding chair side mannerism and friendly staff. Dr. Anderson's work ethic is outstanding as well as the time he spends on each patient's dental care. I would never choose another endodontist to see.",
  },
  {
    id: 136,
    name: "Doug Johnson",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 137,
    name: "M&Ms slime CHANNEL",
    rating: 5,
    source: "Google Review",
    quote: "Amazing experience with this office. Root canal is not fun but they sure tried to make it as comfortable as possible. The office was homey, beautiful and spectacularly clean. The staff were attentive and polite. I recommend Dr Anderson to anyone who needs a root canal.",
  },
  {
    id: 138,
    name: "Barbara Davilman",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson and his staff make getting a root canal painless and easy - like getting a cavity filled. I felt like I was in the hands of a perfectionist who took great care of me and who took great pride in his work. Very rare these days. Can not recommend highly enough.",
  },
  {
    id: 139,
    name: "Chuck Rose",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 140,
    name: "David Lifschitz",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson is a consummate professional. He was attentive, quick and took care to eliminate as much pain as possible during my root canal treatment. He kept me informed every step of the way and took time to call me in the evening and check to see that I experienced no pain or discomfort. I highly recommend his service for anyone in need of a root canal treatment.",
  },
  {
    id: 141,
    name: "Bill Williams",
    rating: 5,
    source: "Google Review",
    quote: "Great chair side manner.",
  },
  {
    id: 142,
    name: "Ronny Shahrabani",
    rating: 5,
    source: "Google Review",
    quote: "Virtually pain-free root canal. Highly recommend kind and professional service.",
  },
  {
    id: 143,
    name: "Chris Carr",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 144,
    name: "Robert H",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 145,
    name: "Rachel O'Brien",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 146,
    name: "david franco",
    rating: 5,
    source: "Google Review",
    quote: "very professional, courteous & honest",
  },
  {
    id: 147,
    name: "Ben Shamoiel",
    rating: 5,
    source: "Google Review",
    quote: "Great bedside manners. I had let my tooth issue get out of hand. Dr. Anderson was straight forward and gave me the option that fit my needs. Staff is awesome also.",
  },
  {
    id: 148,
    name: "john altman",
    rating: 5,
    source: "Google Review",
    quote: "Very professional, knowledgeable and efficient. Explains procedures clearly and fully. Makes every attempt to maximize comfort and minimize pain. As a physician (who has also undergone several root canal procedures), would recommend Dr Anderson without reservation.",
  },
  {
    id: 149,
    name: "Bryan Jackson",
    rating: 5,
    source: "Google Review",
    quote: "Very professional Staff. Very Thorough and detailed. Excellent skills in communicating with me",
  },
  {
    id: 150,
    name: "Taylor L",
    rating: 5,
    source: "Google Review",
    quote: "Dr.Anderson and his team are amazing. I've never seen a more gentle, caring, compassionate doctor before. My heart is so full. Thank you thank you thank you.",
  },
  {
    id: 151,
    name: "gail fisher",
    rating: 5,
    source: "Google Review",
    quote: "Dr. Anderson and everyone in his office were wonderful. A caring, painless, and fast experience. He called to check on me. What used to be something to dread was \"easy peasey.\"",
  },
  {
    id: 152,
    name: "ingrid Nuernberg",
    rating: 5,
    source: "Google Review",
    quote: "I cannot imagine a more pleasant experience having a root canal than the one I had today (I know that sounds very strange, but this was actually a very positive experience!). Dr. Anderson and Judy were so kind, thoughtful and caring during the entire procedure, always asking how I was doing. I had some unusual circumstances and Dr. Anderson took extra care to assure that I was receiving the right treatment. His dedication and professionalism were both first rate. I'm so happy I was referred to him.",
  },
  {
    id: 153,
    name: "Akiko McCoy",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 154,
    name: "randy landas",
    rating: 5,
    source: "Google Review",
    quote: "I highly recommend Dr Anderson. I was having pain and of course it was the day before I had to travel. He got me in that day. I ended up needing a root canal which he did on the spot. It was a painless procedure and I've had no further problem with tooth. He even followed it up with a personal call to make sure everything was ok.",
  },
  {
    id: 155,
    name: "Lionel Ephraim",
    rating: 5,
    source: "Google Review",
    quote: "Made dental work a very pleasant experience. Quick and efficient in a very friendly atmosphere. Staff could not be more friendly and knowledgeable. Definitely recommend.",
  },
  {
    id: 156,
    name: "Stephen DeCordova",
    rating: 5,
    source: "Google Review",
    quote: "Dr Anderson added me to his schedule at the last minute (same day) at the request of my referring dentist. Yet, he was extraordinarily generous with his time, taking whatever time was needed to understand everything about my atypical and somewhat involved case. I experienced no pain during the procedure, and am absolutely pain-free now. I recommend Dr. Anderson wholeheartedly and without reservation.",
  },
  {
    id: 157,
    name: "andrew bjurman",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 158,
    name: "Jeff K",
    rating: 5,
    source: "Google Review",
    quote: "Rating only (no written review).",
  },
  {
    id: 159,
    name: "Kevin Michael Martin",
    rating: 5,
    source: "Google Review",
    quote: "They took amazing care of me with my root canal and my crazy schedule. I would recommend them to anyone in the Los Angeles area!",
  },
  {
    id: 160,
    name: "Hollywood Hills Suites",
    rating: 5,
    source: "Google Review",
    quote: "thorough, detail oriented, professional and excellent treatment provider. Highly recommend Dr Anderson.",
  },
  {
    id: 161,
    name: "L. Villagomez",
    rating: 5,
    source: "Google Review",
    quote: "I'm so grateful Dr. Anderson took the pain away from an infection caused by a root canal that was done incorrectly by another Dentist. He is precise and cares greatly about the recovery of his patients. Thank you Dr. & all staff!",
  },
]
